services:

  tfg-nginx:
    container_name: TFG-nginx
    image: nginx:stable
    ports:
      - 9001:80
    volumes:
      - ./nginx/conf/default.conf.template:/etc/nginx/templates/default.conf.template
      #- ./nginx/conf/backend.conf:/etc/nginx/sites-available/api_tournament.conf
      - ./../backend:/var/www/html/backend
      #- ./../frontend:/var/www/html/frontend
    environment:
      - PHP_CONTAINER_NAME=TFG-php
    depends_on:
      - tfg-backend
    networks:
      - tfg
      - internal

  tfg-backend:
    container_name: TFG-php
    build:
      context: ./php
    user: ${UID}:${GID}
    volumes:
      - ./../backend:/var/www/html/backend
      - ./php/conf/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      PHP_IDE_CONFIG: serverName=TFG
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005
    depends_on:
      - tfg-database
    networks:
       - tfg
       - internal

  tfg-database:
    container_name: TFG-database
    image: postgres
    ports:
      - 9002:5432
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata:cached
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
      PGDATA: /var/lib/postgres/data/pgdata
    networks:
      - tfg
      - internal

  tfg-mail-catcher:
    container_name: TFG-mail_catcher
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - tfg
      - internal


volumes:
  postgres:

networks:
  tfg:
    external: true
  internal:
    driver: bridge
    internal: true
